"""alter_user_remove_api_key

Revision ID: 98279a994a24
Revises: 0a3d844c3c53
Create Date: 2025-04-11 10:26:34.980472+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98279a994a24'
down_revision = '0a3d844c3c53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ### 