version: '3.8'
services:
  besu:
    image: hyperledger/besu:latest
    container_name: besu-node
    ports:
      - "8545:8545"
      - "30303:30303"
    command: >
      --network=dev
      --rpc-http-enabled
      --rpc-http-api=ADMIN,CLIQUE,ETH,NET,TXPOOL,WEB3,DEBUG
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --p2p-port=30303
      --node-private-key-file=/keys/besu_key.txt
      --data-path=/var/lib/besu
      --host-allowlist=*
      --rpc-http-cors-origins=*
      --miner-enabled
      --miner-coinbase=0x73682E80eAeB9A7c65b67c318cCc07C227748aE0
#      --genesis-file=/config/genesis.json
    volumes:
      - /Users/huyhanhat/Documents/My_Projects/study/Blockchain/docker/besu-node/volume:/var/lib/besu
      - /Users/huyhanhat/Documents/My_Projects/study/Blockchain/scripts/besu_key.txt:/keys/besu_key.txt:ro
      # - ${PWD}/docker/besu-node/config/genesis.json:/config/genesis.json:ro

  ethsigner:
    image: consensys/ethsigner:latest
    platform: linux/amd64
    container_name: ethsigner
    ports:
      - "8555:8545"  # EthSigner container lắng nghe trên cổng 8545, ánh xạ ra cổng 8555 trên host
    command: >
      --chain-id=1337
      --http-listen-host=0.0.0.0
      --http-listen-port=8545
      --downstream-http-host=besu
      --downstream-http-port=8545
      file-based-signer -k /opt/ethsigner/keyfile -p /opt/ethsigner/passwordfile
    volumes:
      - /Users/huyhanhat/Documents/My_Projects/study/Blockchain/scripts/keystore.json:/opt/ethsigner/keyfile:ro
      - /Users/huyhanhat/Documents/My_Projects/study/Blockchain/scripts/password.txt:/opt/ethsigner/passwordfile:ro
    depends_on:
      - besu
volumes:
  besu_data: